export const ADD = "ADD"
export const EDIT = "EDIT"
export const REMOVE = "REMOVE"
export const ADDCOMMENT = "ADDCOMMENT"
export const DELETECOMMENT = "DELETECOMMENT"
export const LOCALLOAD = "LOCALLOAD"